server:
  port: 6010
spring: 
  application: 
    name: cloud-admin
  security:
    user:
      name: root
      password: root
  # 邮件设置
  mail:
    host: smtp.qq.com
    username: 1399979641
    password: btpkjrjjrhsvgaff
    properties:
      mail: 
        smpt: 
          auth: true
          starttls: 
            enable: true
            required: true
#收件邮箱
spring.boot.admin.notify.mail.to: 2634982208@qq.com   
# 发件邮箱
spring.boot.admin.notify.mail.from: 1399979641@qq.com   
      
#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7900:7900/eureka/
  instance: 
    hostname: localhost
    lease-renewal-interval-in-seconds: 1

management:
  endpoints:
    web:
      exposure:
        #yml加双引号，properties不用加
        include: "*"    
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true   